---
name: 'Sync project'

on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 'set shell options globally'
        run: set -euxo pipefail
        shell: bash

      - name: 'checkout source repo'
        uses: actions/checkout@v3
        with:
          repository: dev1-sg/project
          token: ${{secrets.GH_TOKEN}}
          path: source

      - name: 'sync to profile'
        run: |
          rsync -av --delete --exclude='.git' --exclude='.github' source/ profile/
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync from dev1-sg/project"
          git push
